name: Deploy to Replicate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Replicate
        uses: replicate/deploy@v1
        with:
          token: ${{ secrets.REPLICATE_TOKEN }}
          model: ${{ secrets.REPLICATE_MODEL }}
          # Use faster build settings
          build_args: |
            --no-cache
            --progress=plain
